"""Post-process nested-grouping-plan.yaml (divider absorption, etc.).

Extracted from postprocess-grouping-plan.sh (Issue 253 refactor).
Parses the plan YAML, applies absorb_stage_c_dividers per section,
and outputs the modified YAML.
"""

import json
import sys

from .comparison import absorb_stage_c_dividers

__all__ = [
    "format_plan_yaml",
    "parse_plan_yaml",
    "postprocess_plan",
]


def parse_plan_yaml(lines):
    """Parse nested-grouping-plan.yaml into section structures.

    Args:
        lines: List of raw lines from the YAML file

    Returns:
        List of section dicts, each with:
          - section_name: str
          - section_id: str
          - total_children: str
          - header_lines: list of original header lines
          - groups: list of group dicts (name, pattern, node_ids, reason)
    """
    sections = []
    current_section = None
    current_group = None

    for line in lines:
        stripped = line.strip()
        if stripped.startswith('- section_name:'):
            if current_section is not None:
                if current_group is not None:
                    current_section['groups'].append(current_group)
                sections.append(current_section)
            current_section = {
                'section_name': stripped.split(':', 1)[1].strip().strip('"'),
                'header_lines': [line],
                'groups': []
            }
            current_group = None
        elif current_section is not None and stripped.startswith('section_id:'):
            current_section['section_id'] = stripped.split(':', 1)[1].strip().strip('"')
            current_section['header_lines'].append(line)
        elif current_section is not None and stripped.startswith('total_children:'):
            current_section['total_children'] = stripped.split(':', 1)[1].strip()
            current_section['header_lines'].append(line)
        elif current_section is not None and stripped.startswith('groups:'):
            current_section['header_lines'].append(line)
        elif stripped.startswith('- name:'):
            if current_group is not None and current_section is not None:
                current_section['groups'].append(current_group)
            name = stripped.split(':', 1)[1].strip().strip('"')
            current_group = {'name': name, 'pattern': '', 'node_ids': [], 'reason': ''}
        elif current_group is not None:
            if stripped.startswith('pattern:'):
                current_group['pattern'] = stripped.split(':', 1)[1].strip().strip('"')
            elif stripped.startswith('node_ids:'):
                try:
                    current_group['node_ids'] = json.loads(stripped.split(':', 1)[1].strip())
                except json.JSONDecodeError as e:
                    print(f"Warning: Failed to parse node_ids in group '{current_group.get('name', '?')}', defaulting to empty: {e}", file=sys.stderr)
                    current_group['node_ids'] = []
            elif stripped.startswith('reason:'):
                current_group['reason'] = stripped.split(':', 1)[1].strip().strip('"')

    if current_group is not None and current_section is not None:
        current_section['groups'].append(current_group)
    if current_section is not None:
        sections.append(current_section)

    return sections


def format_plan_yaml(sections, total_absorbed):
    """Format sections back into YAML text.

    Args:
        sections: List of section dicts (post-processed)
        total_absorbed: Total number of dividers absorbed

    Returns:
        YAML string
    """
    lines = []
    lines.append('# Nested Grouping Plan (Stage C)')
    lines.append('# Generated by /figma-prepare Phase 2 Stage C')
    lines.append(f'# Post-processed: {total_absorbed} divider(s) absorbed (Issue 253)')
    lines.append('')
    lines.append('sections:')
    for section in sections:
        lines.append(f'  - section_name: "{section["section_name"]}"')
        lines.append(f'    section_id: "{section.get("section_id", "")}"')
        lines.append(f'    total_children: {section.get("total_children", 0)}')
        lines.append(f'    groups:')
        for g in section['groups']:
            lines.append(f'      - name: "{g["name"]}"')
            lines.append(f'        pattern: "{g["pattern"]}"')
            lines.append(f'        node_ids: {json.dumps(g["node_ids"])}')
            lines.append(f'        reason: "{g["reason"]}"')
    return '\n'.join(lines)


def postprocess_plan(plan_file):
    """Post-process a nested-grouping-plan.yaml file.

    Applies divider absorption per section.

    Args:
        plan_file: Path to nested-grouping-plan.yaml

    Returns:
        Tuple of (output_text, total_absorbed, exit_code)
          - output_text: Modified YAML (or original if no changes)
          - total_absorbed: Number of dividers absorbed
          - exit_code: 0=modified, 2=no changes
    """
    with open(plan_file, 'r') as f:
        lines = f.readlines()

    sections = parse_plan_yaml(lines)

    # Apply divider absorption per section (name-based, no metadata needed)
    total_absorbed = 0
    for section in sections:
        before_count = len(section['groups'])
        section['groups'] = absorb_stage_c_dividers(section['groups'])
        absorbed = before_count - len(section['groups'])
        total_absorbed += absorbed
        if absorbed > 0:
            print(f"  Absorbed {absorbed} divider(s) in section '{section['section_name']}'", file=sys.stderr)

    if total_absorbed == 0:
        print('No dividers to absorb.', file=sys.stderr)
        # Return original file unchanged
        with open(plan_file, 'r') as f:
            return f.read(), 0, 2

    output_text = format_plan_yaml(sections, total_absorbed)
    print(f'Absorbed {total_absorbed} divider group(s) into adjacent groups.', file=sys.stderr)
    return output_text, total_absorbed, 0
