"""Stage C YAML I/O and enriched table parsing.

Extracted from stage_c.py for maintainability.
Provides parse_plan_yaml(), write_plan_yaml(), _write_group_yaml(), parse_enriched_table().
"""

import json
import sys

__all__ = [
    'parse_plan_yaml',
    'write_plan_yaml',
    'parse_enriched_table',
]


# ---------------------------------------------------------------------------
# YAML I/O
# ---------------------------------------------------------------------------

def parse_plan_yaml(plan_file):
    """Parse nested-grouping-plan.yaml into structured data."""
    try:
        import yaml
        with open(plan_file, 'r') as f:
            return yaml.safe_load(f)
    except ImportError:
        pass

    # Fallback: simple line-based parser
    with open(plan_file, 'r') as f:
        lines = f.readlines()

    sections = []
    current_section = None
    current_group = None

    for line in lines:
        stripped = line.strip()
        if stripped.startswith('- section_name:'):
            if current_section is not None:
                if current_group is not None:
                    current_section['groups'].append(current_group)
                sections.append(current_section)
            current_section = {
                'section_name': stripped.split(':', 1)[1].strip().strip('"'),
                'groups': []
            }
            current_group = None
        elif current_section is not None and stripped.startswith('section_id:'):
            current_section['section_id'] = stripped.split(':', 1)[1].strip().strip('"')
        elif current_section is not None and stripped.startswith('total_children:'):
            current_section['total_children'] = int(stripped.split(':', 1)[1].strip())
        elif stripped.startswith('- name:') and current_section is not None:
            if current_group is not None:
                current_section['groups'].append(current_group)
            name = stripped.split(':', 1)[1].strip().strip('"')
            current_group = {'name': name, 'pattern': '', 'node_ids': [], 'reason': ''}
        elif current_group is not None:
            if stripped.startswith('pattern:'):
                current_group['pattern'] = stripped.split(':', 1)[1].strip().strip('"')
            elif stripped.startswith('node_ids:'):
                try:
                    current_group['node_ids'] = json.loads(stripped.split(':', 1)[1].strip())
                except json.JSONDecodeError as e:
                    print(f"Warning: Failed to parse node_ids in group '{current_group.get('name', '?')}', defaulting to empty: {e}", file=sys.stderr)
                    current_group['node_ids'] = []
            elif stripped.startswith('reason:'):
                current_group['reason'] = stripped.split(':', 1)[1].strip().strip('"')

    if current_group is not None and current_section is not None:
        current_section['groups'].append(current_group)
    if current_section is not None:
        sections.append(current_section)

    return {'sections': sections}


def write_plan_yaml(plan_data, output_file):
    """Write plan data to YAML file with sub_groups support."""
    lines = []
    lines.append('# Nested Grouping Plan (Stage C)')
    lines.append('# Generated by /figma-prepare Phase 2 Stage C')
    lines.append('# With depth recursion (Issue 257)')
    lines.append('')
    lines.append('sections:')

    for section in plan_data.get('sections', []):
        lines.append(f'  - section_name: "{section["section_name"]}"')
        lines.append(f'    section_id: "{section.get("section_id", "")}"')
        lines.append(f'    total_children: {section.get("total_children", 0)}')
        lines.append(f'    groups:')
        for g in section.get('groups', []):
            _write_group_yaml(lines, g, indent=6)

    with open(output_file, 'w') as f:
        f.write('\n'.join(lines) + '\n')


def _write_group_yaml(lines, group, indent=6):
    """Write a single group (with recursive sub_groups) to YAML lines."""
    pad = ' ' * indent
    lines.append(f'{pad}- name: "{group["name"]}"')
    lines.append(f'{pad}  pattern: "{group.get("pattern", "single")}"')
    lines.append(f'{pad}  node_ids: {json.dumps(group.get("node_ids", []))}')
    if group.get('reason'):
        lines.append(f'{pad}  reason: "{group["reason"]}"')

    sub_groups = group.get('sub_groups', [])
    if sub_groups:
        lines.append(f'{pad}  sub_groups:')
        for sg in sub_groups:
            _write_group_yaml(lines, sg, indent=indent + 4)


# ---------------------------------------------------------------------------
# Enriched table parsing
# ---------------------------------------------------------------------------

def parse_enriched_table(table_text):
    """Parse enriched table text into list of row dicts."""
    rows = []
    lines = table_text.strip().split('\n')
    if len(lines) < 3:
        return rows

    # Parse header to find column indices
    header = lines[0]
    cols = [c.strip() for c in header.split('|')]

    # Find column positions by name
    col_indices = {}
    for i, c in enumerate(cols):
        if c:
            col_indices[c] = i

    # Parse data rows (skip header and separator)
    for line in lines[2:]:
        parts = [c.strip() for c in line.split('|')]
        if len(parts) < 5:
            continue
        row = {}
        for name, idx in col_indices.items():
            if idx < len(parts):
                row[name] = parts[idx]
        if row.get('ID'):
            rows.append(row)

    return rows
