#!/usr/bin/env python3
"""
Figma REST API 全ページノードデータ一括取得スクリプト

MCPのデイリーリミットを回避し、PAT経由でREST APIを直接叩く。
全ページのノードツリー（テキスト・スタイル・レイアウト含む）をJSON保存。

Usage:
    python3 scripts/figma-fetch-all.py
    python3 scripts/figma-fetch-all.py --depth 10  # ネスト深度指定
    python3 scripts/figma-fetch-all.py --pages 1:2883,1:3514  # 特定ページのみ
"""

import os
import sys
import json
import time
import argparse
from datetime import datetime
from pathlib import Path
from urllib.request import Request, urlopen
from urllib.error import HTTPError

# --- Config ---
DEFAULT_FILE_KEY = "YlUnBdy3BJx2HW0FHSqUDr"
CACHE_DIR = Path(__file__).resolve().parent.parent / ".claude" / "cache" / "figma"
PREFETCH_INFO = CACHE_DIR / "prefetch-info.yaml"
RATE_LIMIT_WAIT = 3  # seconds between requests


def get_token():
    token = os.environ.get("FIGMA_PERSONAL_ACCESS_TOKEN")
    if not token:
        print("ERROR: FIGMA_PERSONAL_ACCESS_TOKEN not set", file=sys.stderr)
        print("Set it in .zshrc or .env: export FIGMA_PERSONAL_ACCESS_TOKEN=figd_xxx", file=sys.stderr)
        sys.exit(1)
    return token


def fetch_pages_from_api(file_key, token):
    """Figma REST API からページ一覧を直接取得"""
    url = f"https://api.figma.com/v1/files/{file_key}?depth=2"
    req = Request(url)
    req.add_header("X-Figma-Token", token)

    try:
        with urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read().decode())
    except HTTPError as e:
        print(f"ERROR: Failed to fetch file info: HTTP {e.code} {e.reason}", file=sys.stderr)
        sys.exit(1)

    pages = []
    file_name = data.get("name", "Unknown")
    doc = data.get("document", {})
    for page in doc.get("children", []):
        for frame in page.get("children", []):
            bbox = frame.get("absoluteBoundingBox", {})
            pages.append({
                "name": frame.get("name", "Unknown"),
                "nodeId": frame.get("id", ""),
                "width": int(bbox.get("width", 0)),
                "height": int(bbox.get("height", 0)),
            })
    return pages, file_name


def save_prefetch_info(file_key, pages, file_name="Unknown"):
    """ページ一覧を prefetch-info.yaml に保存"""
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
    lines = [
        f"# Auto-generated by figma-fetch-all.py",
        f"# {timestamp}",
        f"fileKey: \"{file_key}\"",
        f"fileName: \"{file_name}\"",
        f"fetchedAt: \"{timestamp}\"",
        f"pages:",
    ]
    for p in pages:
        lines.append(f"  - name: \"{p['name']}\"")
        lines.append(f"    nodeId: \"{p['nodeId']}\"")
        lines.append(f"    width: {p.get('width', 0)}")
        lines.append(f"    height: {p.get('height', 0)}")
        url = f"https://www.figma.com/design/{file_key}/?node-id={p['nodeId'].replace(':', '%3A')}"
        lines.append(f"    url: \"{url}\"")

    with open(PREFETCH_INFO, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Saved prefetch-info.yaml ({len(pages)} pages)")


def load_pages(file_key, token, filter_ids=None):
    """prefetch-info.yaml があれば読み込み、なければ API から取得"""
    pages = None

    if PREFETCH_INFO.exists():
        try:
            import yaml
            with open(PREFETCH_INFO) as f:
                data = yaml.safe_load(f)
            pages = data.get("pages", [])
        except ImportError:
            # yaml がなければ簡易パース
            pages = []
            current = {}
            with open(PREFETCH_INFO) as f:
                for line in f:
                    line = line.rstrip()
                    if line.strip().startswith("- name:"):
                        if current:
                            pages.append(current)
                        current = {"name": line.split('"')[1] if '"' in line else line.split(":")[1].strip()}
                    elif "nodeId:" in line:
                        current["nodeId"] = line.split('"')[1] if '"' in line else line.split(":")[1].strip()
                    elif "height:" in line:
                        try:
                            current["height"] = int(float(line.split(":")[1].strip()))
                        except ValueError:
                            current["height"] = 0
                if current:
                    pages.append(current)

    if not pages:
        print("No prefetch-info.yaml found. Fetching page list from API...")
        pages, file_name = fetch_pages_from_api(file_key, token)
        # Save to prefetch-info.yaml for other tools
        save_prefetch_info(file_key, pages, file_name)

    if filter_ids:
        pages = [p for p in pages if p.get("nodeId") in filter_ids]
    return pages


def fetch_node(file_key, token, node_id, depth=None):
    """Figma REST API でノードデータを取得"""
    url = f"https://api.figma.com/v1/files/{file_key}/nodes?ids={node_id}"
    if depth:
        url += f"&depth={depth}"

    req = Request(url)
    req.add_header("X-Figma-Token", token)

    try:
        with urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read().decode())
            # Rate limit headers
            remaining = resp.headers.get("X-RateLimit-Remaining", "?")
            return data, remaining
    except HTTPError as e:
        if e.code == 429:
            retry_after = int(e.headers.get("Retry-After", 30))
            print(f"  Rate limited. Waiting {retry_after}s...")
            time.sleep(retry_after)
            return fetch_node(file_key, token, node_id, depth)  # retry
        else:
            print(f"  HTTP {e.code}: {e.reason}", file=sys.stderr)
            return None, None


def extract_stats(node_data):
    """ノードデータから統計情報を抽出"""
    text_count = 0
    total_nodes = 0

    def walk(node):
        nonlocal text_count, total_nodes
        total_nodes += 1
        if node.get("type") == "TEXT":
            text_count += 1
        for child in node.get("children", []):
            walk(child)

    if node_data:
        nodes = node_data.get("nodes", {})
        for nid, ndata in nodes.items():
            doc = ndata.get("document", {})
            walk(doc)

    return total_nodes, text_count


def detect_overflow(node_data, threshold=20):
    """子ノードが親のbboxをはみ出しているケースを検出

    threshold: はみ出し量の閾値(px)。ストロークやアンチエイリアスによる
               微小なはみ出しを無視する。デフォルト20px。

    Returns list of dicts with:
      - parent/child IDs and names
      - overflow directions and amounts
      - parent_size, child_size, offset_from_parent (事実データ)
      - note (自然言語の実装ヒント)
    """
    warnings = []

    def check_children(parent):
        bbox = parent.get("absoluteBoundingBox")
        if not bbox:
            return
        px, py = bbox.get("x", 0), bbox.get("y", 0)
        pw, ph = bbox.get("width", 0), bbox.get("height", 0)

        for child in parent.get("children", []):
            cb = child.get("absoluteBoundingBox")
            if not cb:
                continue
            cx, cy = cb.get("x", 0), cb.get("y", 0)
            cw, ch = cb.get("width", 0), cb.get("height", 0)

            dirs = []
            overflow_left = px - cx
            overflow_top = py - cy
            overflow_right = (cx + cw) - (px + pw)
            overflow_bottom = (cy + ch) - (py + ph)

            if overflow_left > threshold:
                dirs.append(f"left:{overflow_left:.0f}px")
            if overflow_top > threshold:
                dirs.append(f"top:{overflow_top:.0f}px")
            if overflow_right > threshold:
                dirs.append(f"right:{overflow_right:.0f}px")
            if overflow_bottom > threshold:
                dirs.append(f"bottom:{overflow_bottom:.0f}px")

            if dirs:
                # Build natural language note
                dir_descriptions = []
                for d in dirs:
                    side, amount = d.split(":")
                    dir_descriptions.append(f"{amount} beyond parent {side} edge")
                note = (
                    f"Decorative element \"{child.get('name', '?')}\" overflows "
                    f"{', '.join(dir_descriptions)}. "
                    f"Parent needs overflow:hidden. "
                    f"Element is positioned at "
                    f"top:{cy - py:.0f}px left:{cx - px:.0f}px from parent origin "
                    f"with intentional overflow."
                )

                warnings.append({
                    "parent": parent.get("id"),
                    "child": child.get("id"),
                    "child_name": child.get("name", "?"),
                    "overflow": dirs,
                    "parent_size": {"width": round(pw), "height": round(ph)},
                    "child_size": {"width": round(cw), "height": round(ch)},
                    "offset_from_parent": {
                        "top": round(cy - py),
                        "left": round(cx - px),
                    },
                    "note": note,
                })

            # 再帰的にチェック
            check_children(child)

    if node_data:
        nodes = node_data.get("nodes", {})
        for nid, ndata in nodes.items():
            doc = ndata.get("document", {})
            check_children(doc)

    return warnings


def main():
    parser = argparse.ArgumentParser(description="Figma REST API full page fetch")
    parser.add_argument("--file-key", type=str, default=DEFAULT_FILE_KEY, help=f"Figma file key (default: {DEFAULT_FILE_KEY})")
    parser.add_argument("--depth", type=int, default=None, help="Node tree depth (default: full)")
    parser.add_argument("--pages", type=str, default=None, help="Comma-separated nodeIds to fetch")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be fetched")
    args = parser.parse_args()

    file_key = args.file_key
    token = get_token()
    filter_ids = set(args.pages.split(",")) if args.pages else None
    pages = load_pages(file_key, token, filter_ids)

    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    CACHE_DIR.mkdir(parents=True, exist_ok=True)

    print(f"Figma REST API Fetch - {len(pages)} pages")
    print(f"File: {file_key}")
    print(f"Depth: {'full' if not args.depth else args.depth}")
    print(f"Output: {CACHE_DIR}/")
    print("=" * 60)

    if args.dry_run:
        for p in pages:
            print(f"  Would fetch: {p['nodeId']:10s}  {p['name']}")
        return

    results = []
    for i, page in enumerate(pages):
        node_id = page["nodeId"]
        name = page["name"]
        print(f"\n[{i+1}/{len(pages)}] {name} ({node_id})...", end=" ", flush=True)

        data, remaining = fetch_node(file_key, token, node_id, args.depth)
        if data is None:
            print("FAILED")
            results.append({"name": name, "nodeId": node_id, "status": "error"})
            continue

        # Save
        safe_id = node_id.replace(":", "-")
        out_file = CACHE_DIR / f"{file_key}_{safe_id}_{timestamp}_rest.json"
        with open(out_file, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False)

        size = out_file.stat().st_size
        total_nodes, text_count = extract_stats(data)
        print(f"OK  {size:>8,} bytes  ({total_nodes} nodes, {text_count} texts)  [remaining: {remaining}]")

        # Overflow detection (decorative elements exceeding artboard)
        overflows = detect_overflow(data)
        overflow_warnings = []
        if overflows:
            # Only report top-level overflows (direct children of page frame)
            top_level = [o for o in overflows if o["parent"] == node_id]
            for o in top_level:
                dirs_str = " ".join(o["overflow"])
                print(f"  ⚠OVERFLOW [{o['child']}] \"{o['child_name']}\" {dirs_str}")
                overflow_warnings.append({
                    "child_id": o["child"],
                    "child_name": o["child_name"],
                    "directions": o["overflow"],
                    "parent_size": o["parent_size"],
                    "child_size": o["child_size"],
                    "offset_from_parent": o["offset_from_parent"],
                    "note": o["note"],
                })

        results.append({
            "name": name,
            "nodeId": node_id,
            "file": out_file.name,
            "size": size,
            "total_nodes": total_nodes,
            "text_count": text_count,
            "overflow_count": len(overflow_warnings),
            "overflow_warnings": overflow_warnings,
        })

        # Rate limit courtesy wait
        if i < len(pages) - 1:
            time.sleep(RATE_LIMIT_WAIT)

    # Summary
    print("\n" + "=" * 60)
    print("Summary:")
    total_size = sum(r.get("size", 0) for r in results)
    ok_count = sum(1 for r in results if r.get("size", 0) > 0)
    total_overflows = sum(r.get("overflow_count", 0) for r in results)
    print(f"  Fetched: {ok_count}/{len(pages)} pages")
    print(f"  Total size: {total_size:,} bytes ({total_size/1024:.0f} KB)")
    if total_overflows > 0:
        print(f"  ⚠OVERFLOW: {total_overflows} element(s) exceed artboard — apply overflow:hidden in CSS")

    # Save overflow warnings to file for implement to read
    all_overflows = {}
    for r in results:
        if r.get("overflow_warnings"):
            all_overflows[r["nodeId"]] = {
                "page": r["name"],
                "warnings": r["overflow_warnings"],
            }
    overflow_file = CACHE_DIR / "overflow-warnings.json"
    with open(overflow_file, "w", encoding="utf-8") as f:
        json.dump(all_overflows, f, indent=2, ensure_ascii=False)
    if all_overflows:
        print(f"  Overflow warnings saved to: {overflow_file}")


if __name__ == "__main__":
    main()
