#!/usr/bin/env bash
# Post-process nested-grouping-plan.yaml to absorb single-element dividers
# into adjacent list-item groups (Issue 253).
#
# Usage: bash postprocess-grouping-plan.sh <nested-grouping-plan.yaml>
# Output: Modified YAML to stdout (redirect to overwrite the file)
# Exit: 0=success (with modifications), 1=error, 2=no changes needed

set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage: postprocess-grouping-plan.sh <plan.yaml>" >&2
  exit 1
fi

PLAN_FILE="$1"

if [[ ! -f "$PLAN_FILE" ]]; then
  echo "ERROR: Plan file not found: $PLAN_FILE" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

python3 -c "
import json, sys, os
sys.path.insert(0, os.path.join(sys.argv[1], 'lib'))
from figma_utils import absorb_stage_c_dividers

plan_file = sys.argv[2]

# Parse YAML plan (simple line-based parser)
with open(plan_file, 'r') as f:
    lines = f.readlines()

# Extract sections and their groups
sections = []
current_section = None
current_group = None

for line in lines:
    stripped = line.strip()
    if stripped.startswith('- section_name:'):
        if current_section is not None:
            if current_group is not None:
                current_section['groups'].append(current_group)
            sections.append(current_section)
        current_section = {
            'section_name': stripped.split(':', 1)[1].strip().strip('\"'),
            'header_lines': [line],
            'groups': []
        }
        current_group = None
    elif current_section is not None and stripped.startswith('section_id:'):
        current_section['section_id'] = stripped.split(':', 1)[1].strip().strip('\"')
        current_section['header_lines'].append(line)
    elif current_section is not None and stripped.startswith('total_children:'):
        current_section['total_children'] = stripped.split(':', 1)[1].strip()
        current_section['header_lines'].append(line)
    elif current_section is not None and stripped.startswith('groups:'):
        current_section['header_lines'].append(line)
    elif stripped.startswith('- name:'):
        if current_group is not None and current_section is not None:
            current_section['groups'].append(current_group)
        name = stripped.split(':', 1)[1].strip().strip('\"')
        current_group = {'name': name, 'pattern': '', 'node_ids': [], 'reason': ''}
    elif current_group is not None:
        if stripped.startswith('pattern:'):
            current_group['pattern'] = stripped.split(':', 1)[1].strip().strip('\"')
        elif stripped.startswith('node_ids:'):
            try:
                current_group['node_ids'] = json.loads(stripped.split(':', 1)[1].strip())
            except json.JSONDecodeError:
                current_group['node_ids'] = []
        elif stripped.startswith('reason:'):
            current_group['reason'] = stripped.split(':', 1)[1].strip().strip('\"')

if current_group is not None and current_section is not None:
    current_section['groups'].append(current_group)
if current_section is not None:
    sections.append(current_section)

# Apply divider absorption per section (name-based, no metadata needed)
total_absorbed = 0
for section in sections:
    before_count = len(section['groups'])
    section['groups'] = absorb_stage_c_dividers(section['groups'])
    absorbed = before_count - len(section['groups'])
    total_absorbed += absorbed
    if absorbed > 0:
        print(f\"  Absorbed {absorbed} divider(s) in section '{section['section_name']}'\", file=sys.stderr)

if total_absorbed == 0:
    print('No dividers to absorb.', file=sys.stderr)
    # Output original file unchanged
    with open(plan_file, 'r') as f:
        sys.stdout.write(f.read())
    sys.exit(2)

# Output modified YAML
print('# Nested Grouping Plan (Stage C)')
print('# Generated by /figma-prepare Phase 2 Stage C')
print(f'# Post-processed: {total_absorbed} divider(s) absorbed (Issue 253)')
print()
print('sections:')
for section in sections:
    print(f'  - section_name: \"{section[\"section_name\"]}\"')
    print(f'    section_id: \"{section.get(\"section_id\", \"\")}\"')
    print(f'    total_children: {section.get(\"total_children\", 0)}')
    print(f'    groups:')
    for g in section['groups']:
        print(f'      - name: \"{g[\"name\"]}\"')
        print(f'        pattern: \"{g[\"pattern\"]}\"')
        print(f'        node_ids: {json.dumps(g[\"node_ids\"])}')
        print(f'        reason: \"{g[\"reason\"]}\"')

print(f'Absorbed {total_absorbed} divider group(s) into adjacent groups.', file=sys.stderr)
sys.exit(0)
" "${SCRIPT_DIR}/.." "$PLAN_FILE"
