#!/usr/bin/env python3
"""
Stage C Depth Recursion - Heuristic sub-grouping within nested-grouping-plan.yaml.

Recursively sub-groups within each group's sibling nodes using enriched table
metadata (Col column, spatial proximity, pattern recognition). No LLM calls
needed — fully deterministic.

Usage:
  python3 run-stage-c-depth-recursion.py \
    --metadata .claude/cache/figma/prepare-metadata-{nodeId}.json \
    --plan .claude/cache/figma/nested-grouping-plan.yaml \
    [--max-depth 10] [--dry-run]

Output:
  Updates --plan in-place with sub_groups added at each depth level.
  Prints summary to stderr.

Exit codes:
  0 = success (sub_groups added)
  1 = error
  2 = no changes (already converged or no recursion targets)
"""

import json
import sys
import os
import re
import subprocess
import argparse
from copy import deepcopy

# Add lib to path
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SKILLS_DIR = os.path.dirname(SCRIPT_DIR)
sys.path.insert(0, os.path.join(SKILLS_DIR, 'lib'))

from figma_utils import (
    load_metadata, get_root_node, resolve_absolute_coords,
    get_bbox, find_node_by_id, generate_enriched_table
)


def parse_plan_yaml(plan_file):
    """Parse nested-grouping-plan.yaml into structured data."""
    try:
        import yaml
        with open(plan_file, 'r') as f:
            return yaml.safe_load(f)
    except ImportError:
        pass

    # Fallback: simple line-based parser
    with open(plan_file, 'r') as f:
        lines = f.readlines()

    sections = []
    current_section = None
    current_group = None

    for line in lines:
        stripped = line.strip()
        if stripped.startswith('- section_name:'):
            if current_section is not None:
                if current_group is not None:
                    current_section['groups'].append(current_group)
                sections.append(current_section)
            current_section = {
                'section_name': stripped.split(':', 1)[1].strip().strip('"'),
                'groups': []
            }
            current_group = None
        elif current_section is not None and stripped.startswith('section_id:'):
            current_section['section_id'] = stripped.split(':', 1)[1].strip().strip('"')
        elif current_section is not None and stripped.startswith('total_children:'):
            current_section['total_children'] = int(stripped.split(':', 1)[1].strip())
        elif stripped.startswith('- name:') and current_section is not None:
            if current_group is not None:
                current_section['groups'].append(current_group)
            name = stripped.split(':', 1)[1].strip().strip('"')
            current_group = {'name': name, 'pattern': '', 'node_ids': [], 'reason': ''}
        elif current_group is not None:
            if stripped.startswith('pattern:'):
                current_group['pattern'] = stripped.split(':', 1)[1].strip().strip('"')
            elif stripped.startswith('node_ids:'):
                try:
                    current_group['node_ids'] = json.loads(stripped.split(':', 1)[1].strip())
                except json.JSONDecodeError:
                    current_group['node_ids'] = []
            elif stripped.startswith('reason:'):
                current_group['reason'] = stripped.split(':', 1)[1].strip().strip('"')

    if current_group is not None and current_section is not None:
        current_section['groups'].append(current_group)
    if current_section is not None:
        sections.append(current_section)

    return {'sections': sections}


def write_plan_yaml(plan_data, output_file):
    """Write plan data to YAML file with sub_groups support."""
    lines = []
    lines.append('# Nested Grouping Plan (Stage C)')
    lines.append('# Generated by /figma-prepare Phase 2 Stage C')
    lines.append('# With depth recursion (Issue 257)')
    lines.append('')
    lines.append('sections:')

    for section in plan_data.get('sections', []):
        lines.append(f'  - section_name: "{section["section_name"]}"')
        lines.append(f'    section_id: "{section.get("section_id", "")}"')
        lines.append(f'    total_children: {section.get("total_children", 0)}')
        lines.append(f'    groups:')
        for g in section.get('groups', []):
            _write_group_yaml(lines, g, indent=6)

    with open(output_file, 'w') as f:
        f.write('\n'.join(lines) + '\n')


def _write_group_yaml(lines, group, indent=6):
    """Write a single group (with recursive sub_groups) to YAML lines."""
    pad = ' ' * indent
    lines.append(f'{pad}- name: "{group["name"]}"')
    lines.append(f'{pad}  pattern: "{group.get("pattern", "single")}"')
    lines.append(f'{pad}  node_ids: {json.dumps(group.get("node_ids", []))}')
    if group.get('reason'):
        lines.append(f'{pad}  reason: "{group["reason"]}"')

    sub_groups = group.get('sub_groups', [])
    if sub_groups:
        lines.append(f'{pad}  sub_groups:')
        for sg in sub_groups:
            _write_group_yaml(lines, sg, indent=indent + 4)


def parse_enriched_table(table_text):
    """Parse enriched table text into list of row dicts."""
    rows = []
    lines = table_text.strip().split('\n')
    if len(lines) < 3:
        return rows

    # Parse header to find column indices
    header = lines[0]
    cols = [c.strip() for c in header.split('|')]

    # Find column positions by name
    col_indices = {}
    for i, c in enumerate(cols):
        if c:
            col_indices[c] = i

    # Parse data rows (skip header and separator)
    for line in lines[2:]:
        parts = [c.strip() for c in line.split('|')]
        if len(parts) < 5:
            continue
        row = {}
        for name, idx in col_indices.items():
            if idx < len(parts):
                row[name] = parts[idx]
        if row.get('ID'):
            rows.append(row)

    return rows


def heuristic_sub_group(group, sibling_nodes, root_node, page_width, page_height):
    """Apply heuristic sub-grouping to a group's sibling nodes.

    Returns list of sub_groups, or empty list if no meaningful split.
    """
    node_ids = group.get('node_ids', [])
    if len(node_ids) < 3:
        return []

    # Compute bounding box of all siblings
    bboxes = {}
    for node in sibling_nodes:
        nid = node.get('id', '')
        if not nid:
            continue
        bboxes[nid] = get_bbox(node)

    if not bboxes:
        return []

    min_x = min(b['x'] for b in bboxes.values())
    min_y = min(b['y'] for b in bboxes.values())
    max_right = max(b['x'] + b['w'] for b in bboxes.values())
    max_bottom = max(b['y'] + b['h'] for b in bboxes.values())
    group_width = max_right - min_x
    group_height = max_bottom - min_y

    if group_width <= 0 or group_height <= 0:
        return []

    # Generate enriched table to get Col column
    sibling_sorted = sorted(sibling_nodes, key=lambda c: get_bbox(c).get('y', 0))
    enriched = generate_enriched_table(
        sibling_sorted,
        page_width=group_width if group_width > 0 else page_width,
        page_height=group_height if group_height > 0 else page_height,
        root_x=min_x,
        root_y=min_y,
    )

    rows = parse_enriched_table(enriched)
    if not rows:
        return []

    # Strategy 0: Heading separation (top heading elements vs content below)
    heading_groups = _try_heading_split(rows, bboxes, sibling_nodes, group['name'])
    if heading_groups:
        return heading_groups

    # Strategy 1: Column-based split (Col = L/R/F)
    col_groups = _try_column_split(rows, group['name'])
    if col_groups:
        return col_groups

    # Strategy 2: Spatial gap split (large Y gap between element clusters)
    spatial_groups = _try_spatial_split(rows, bboxes, group['name'])
    if spatial_groups:
        return spatial_groups

    # Strategy 3: Y-band clustering (elements at same Y → horizontal row)
    yband_groups = _try_yband_split(rows, bboxes, group['name'])
    if yband_groups:
        return yband_groups

    return []


def _try_heading_split(rows, bboxes, sibling_nodes, parent_name):
    """Split top heading elements from content below (Issue #258).

    Detects a heading pattern at the top of a group:
    - 1-3 elements at the smallest Y positions
    - Heading elements are TEXT or small ELLIPSE/VECTOR (decorations)
    - Clear separation from content below (any gap or divider between)
    """
    HEADING_MAX_ELEMENTS = 3
    HEADING_GAP_MIN = 10  # px - minimum gap between heading bottom and content top

    if len(rows) < 4:  # Need at least heading(1-3) + content(1+) = 4
        return []

    # Build node type lookup from sibling_nodes
    node_types = {}
    for node in sibling_nodes:
        nid = node.get('id', '')
        if not nid:
            continue
        ntype = node.get('type', '')
        node_types[nid] = ntype

    # Sort by Y position
    items = []
    for row in rows:
        nid = row.get('ID', '')
        if nid in bboxes:
            b = bboxes[nid]
            items.append((nid, b['y'], b['y'] + b['h'], node_types.get(nid, '')))

    if len(items) < 4:
        return []

    items.sort(key=lambda x: x[1])  # Sort by y_top

    # Try heading sizes 1, 2, 3
    best_split = None
    for heading_size in range(1, min(HEADING_MAX_ELEMENTS + 1, len(items) - 1)):
        heading_candidates = items[:heading_size]
        content_start = items[heading_size]

        # Check heading candidates are heading-like (TEXT, ELLIPSE, small VECTOR)
        heading_types = [c[3] for c in heading_candidates]
        has_text = any(t == 'TEXT' for t in heading_types)
        all_heading_like = all(
            t in ('TEXT', 'ELLIPSE', 'VECTOR', 'LINE') for t in heading_types
        )

        if not has_text or not all_heading_like:
            continue

        # Check heading elements are small (not content blocks)
        heading_max_h = max(c[2] - c[1] for c in heading_candidates)
        if heading_max_h > 60:  # Heading text shouldn't be taller than 60px
            continue

        # Check gap between heading bottom and content top
        heading_bottom = max(c[2] for c in heading_candidates)
        content_top = content_start[1]
        gap = content_top - heading_bottom

        if gap < HEADING_GAP_MIN:
            continue

        # Found a valid heading split
        best_split = heading_size
        break

    if best_split is None:
        return []

    heading_ids = [items[i][0] for i in range(best_split)]
    content_ids = [items[i][0] for i in range(best_split, len(items))]

    if not heading_ids or len(content_ids) < 2:
        return []

    return [
        {
            'name': f'{parent_name}-heading',
            'pattern': 'single' if len(heading_ids) == 1 else 'list',
            'node_ids': heading_ids,
            'reason': f'heading separation ({len(heading_ids)} elements)',
        },
        {
            'name': f'{parent_name}-content',
            'pattern': 'list',
            'node_ids': content_ids,
            'reason': f'content below heading ({len(content_ids)} elements)',
        },
    ]


def _try_column_split(rows, parent_name):
    """Split by Col column (L/R/F). Returns sub_groups or empty list."""
    left_ids = []
    right_ids = []
    full_ids = []
    other_ids = []

    for row in rows:
        col = row.get('Col', '-')
        nid = row.get('ID', '')
        if not nid:
            continue
        if col == 'L':
            left_ids.append(nid)
        elif col == 'R':
            right_ids.append(nid)
        elif col == 'F':
            full_ids.append(nid)
        else:
            other_ids.append(nid)

    # Need both L and R to split
    if not left_ids or not right_ids:
        return []

    sub_groups = []

    if left_ids:
        sub_groups.append({
            'name': f'{parent_name}-left',
            'pattern': 'single' if len(left_ids) == 1 else 'list',
            'node_ids': left_ids,
            'reason': 'Col=L column split',
        })

    if right_ids:
        sub_groups.append({
            'name': f'{parent_name}-right',
            'pattern': 'single' if len(right_ids) == 1 else 'list',
            'node_ids': right_ids,
            'reason': 'Col=R column split',
        })

    # Full-width elements (dividers, backgrounds) → separate group or absorb
    if full_ids:
        sub_groups.append({
            'name': f'{parent_name}-dividers',
            'pattern': 'single' if len(full_ids) == 1 else 'decoration',
            'node_ids': full_ids,
            'reason': 'Col=F full-width elements',
        })

    # Other/center elements
    if other_ids:
        sub_groups.append({
            'name': f'{parent_name}-center',
            'pattern': 'single' if len(other_ids) == 1 else 'list',
            'node_ids': other_ids,
            'reason': 'Col=C/- center elements',
        })

    return sub_groups


def _try_spatial_split(rows, bboxes, parent_name):
    """Split by large Y gap between element clusters."""
    SPATIAL_GAP_THRESHOLD = 100  # px

    # Sort by Y position
    items = []
    for row in rows:
        nid = row.get('ID', '')
        if nid in bboxes:
            items.append((nid, bboxes[nid]['y']))

    if len(items) < 3:
        return []

    items.sort(key=lambda x: x[1])

    # Find largest Y gap
    gaps = []
    for i in range(len(items) - 1):
        y1_bottom = bboxes[items[i][0]]['y'] + bboxes[items[i][0]]['h']
        y2_top = items[i + 1][1]
        gap = y2_top - y1_bottom
        gaps.append((i, gap))

    if not gaps:
        return []

    max_gap_idx, max_gap = max(gaps, key=lambda x: x[1])

    if max_gap < SPATIAL_GAP_THRESHOLD:
        return []

    # Split at the largest gap
    top_ids = [items[j][0] for j in range(max_gap_idx + 1)]
    bottom_ids = [items[j][0] for j in range(max_gap_idx + 1, len(items))]

    if not top_ids or not bottom_ids:
        return []

    return [
        {
            'name': f'{parent_name}-upper',
            'pattern': 'single' if len(top_ids) == 1 else 'list',
            'node_ids': top_ids,
            'reason': f'spatial split (gap={int(max_gap)}px)',
        },
        {
            'name': f'{parent_name}-lower',
            'pattern': 'single' if len(bottom_ids) == 1 else 'list',
            'node_ids': bottom_ids,
            'reason': f'spatial split (gap={int(max_gap)}px)',
        },
    ]


def _try_yband_split(rows, bboxes, parent_name):
    """Split by Y-band clustering (elements at same Y position → horizontal row).

    Detects icon+title pairs, label+value pairs at the same horizontal row.
    """
    YBAND_TOLERANCE = 20  # px — elements within this Y range form a band

    # Collect items with Y center position
    items = []
    for row in rows:
        nid = row.get('ID', '')
        if nid in bboxes:
            b = bboxes[nid]
            y_center = b['y'] + b['h'] / 2
            items.append((nid, y_center))

    if len(items) < 3:
        return []

    items.sort(key=lambda x: x[1])

    # Group into Y-bands: greedy merge within tolerance
    bands = []
    current_band = [items[0]]
    for i in range(1, len(items)):
        # Compare with the first element in current band (anchor)
        if items[i][1] - current_band[0][1] <= YBAND_TOLERANCE:
            current_band.append(items[i])
        else:
            bands.append(current_band)
            current_band = [items[i]]
    bands.append(current_band)

    # Need 2+ distinct bands AND at least one band with 2+ elements
    if len(bands) < 2:
        return []

    has_multi_element_band = any(len(band) >= 2 for band in bands)
    if not has_multi_element_band:
        return []

    # All bands must be non-trivial split (not just 1 element per band = no grouping benefit)
    # If every band has exactly 1 element, this is just a vertical list — no split needed
    if all(len(band) == 1 for band in bands):
        return []

    sub_groups = []
    for idx, band in enumerate(bands):
        band_ids = [item[0] for item in band]
        if len(band) >= 2:
            label = f'{parent_name}-row-{idx + 1}'
            reason = f'Y-band cluster ({len(band)} elements, y≈{int(band[0][1])})'
        else:
            label = f'{parent_name}-row-{idx + 1}'
            reason = f'Y-band single (y≈{int(band[0][1])})'

        sub_groups.append({
            'name': label,
            'pattern': 'single' if len(band_ids) == 1 else 'list',
            'node_ids': band_ids,
            'reason': reason,
        })

    return sub_groups


def run_depth_recursion(metadata_file, plan_file, max_depth=10, dry_run=False):
    """Main recursion loop: sub-group until convergence."""
    # Load metadata
    data = load_metadata(metadata_file)
    root = get_root_node(data)
    resolve_absolute_coords(root)
    page_bbox = get_bbox(root)
    page_width = page_bbox['w']
    page_height = page_bbox['h']

    # Load plan
    plan = parse_plan_yaml(plan_file)
    if not plan or 'sections' not in plan:
        print('ERROR: Invalid plan file', file=sys.stderr)
        return 1

    total_sub_groups_added = 0

    for depth in range(1, max_depth + 1):
        depth_added = 0

        # Collect all groups that need recursion (across all sections, all depths)
        targets = _collect_recursion_targets(plan)

        if not targets:
            print(f'  Depth {depth}: no recursion targets → converged', file=sys.stderr)
            break

        print(f'  Depth {depth}: {len(targets)} recursion target(s)', file=sys.stderr)

        for target_group, section_name in targets:
            node_ids = target_group.get('node_ids', [])

            # Resolve sibling nodes
            sibling_nodes = []
            for nid in node_ids:
                node = find_node_by_id(root, nid)
                if node:
                    sibling_nodes.append(node)

            if len(sibling_nodes) < 3:
                continue

            # Apply heuristic sub-grouping
            sub_groups = heuristic_sub_group(
                target_group, sibling_nodes, root, page_width, page_height
            )

            if sub_groups:
                target_group['sub_groups'] = sub_groups
                depth_added += len(sub_groups)
                print(
                    f'    {target_group["name"]}: {len(sub_groups)} sub-group(s) '
                    f'({", ".join(sg["name"] for sg in sub_groups)})',
                    file=sys.stderr,
                )

        total_sub_groups_added += depth_added

        if depth_added == 0:
            print(f'  Depth {depth}: no sub-groups produced → converged', file=sys.stderr)
            break

    if total_sub_groups_added == 0:
        print('No sub-groups to add.', file=sys.stderr)
        return 2

    if not dry_run:
        write_plan_yaml(plan, plan_file)
        print(
            f'Updated {plan_file}: {total_sub_groups_added} sub-group(s) added.',
            file=sys.stderr,
        )
    else:
        print(
            f'[dry-run] Would add {total_sub_groups_added} sub-group(s).',
            file=sys.stderr,
        )
        # Print to stdout for inspection
        write_plan_yaml(plan, '/dev/stdout')

    return 0


def _collect_recursion_targets(plan):
    """Collect all groups needing recursion (no existing sub_groups, 3+ node_ids,
    pattern != single or node_ids >= 3)."""
    targets = []
    for section in plan.get('sections', []):
        _collect_from_groups(section.get('groups', []), section['section_name'], targets)
    return targets


def _collect_from_groups(groups, section_name, targets):
    """Recursively collect groups that need sub-grouping."""
    for g in groups:
        # Skip if already has sub_groups
        if g.get('sub_groups'):
            # Recurse into existing sub_groups to find deeper targets
            _collect_from_groups(g['sub_groups'], section_name, targets)
            continue

        node_ids = g.get('node_ids', [])
        pattern = g.get('pattern', 'single')

        # Recursion criteria: pattern != single OR node_ids >= 3
        if pattern != 'single' or len(node_ids) >= 3:
            if len(node_ids) >= 3:  # Need at least 3 to meaningfully split
                targets.append((g, section_name))


def main():
    parser = argparse.ArgumentParser(description='Stage C depth recursion')
    parser.add_argument('--metadata', required=True, help='Metadata JSON file')
    parser.add_argument('--plan', required=True, help='Nested grouping plan YAML')
    parser.add_argument('--max-depth', type=int, default=10, help='Safety upper bound')
    parser.add_argument('--dry-run', action='store_true', help='Preview without writing')
    args = parser.parse_args()

    if not os.path.isfile(args.metadata):
        print(f'ERROR: Metadata file not found: {args.metadata}', file=sys.stderr)
        sys.exit(1)

    if not os.path.isfile(args.plan):
        print(f'ERROR: Plan file not found: {args.plan}', file=sys.stderr)
        sys.exit(1)

    sys.exit(run_depth_recursion(args.metadata, args.plan, args.max_depth, args.dry_run))


if __name__ == '__main__':
    main()
